
GET http://localhost:3030/ HTTP/1.1

### Create new User
#POST http://localhost:3030/create-user HTTP/1.1
POST http://10.23.102.97:3030/create-user HTTP/1.1
content-type: application/json

{
    "name": "Jose",
    "lastname": "Gonzalez",
    "email":"jose@gonzales.com",
    "password":"galloDeOro2022"
}


###Get List Users
GET http://localhost:3030/list-users HTTP/1.1

###Find User / Sign In
POST http://localhost:3030/find-user HTTP/1.1
content-type: application/json

{    
    "email":"carlos@rocha.com",
    "password":"galloDeOro2022"
}

###LogOff
POST http://localhost:3030/logoff HTTP/1.1
content-type: application/json

{    
    "email":"carlos@rocha.com"
}



###Create Post
POST http://localhost:3030/create-post HTTP/1.1
content-type: application/json

{    
    "email":"carlos@rocha.com",
    "post":"Fluyan mis lagrimas dijo el policia"
}

###Get Posts
GET http://localhost:3030/get-posts HTTP/1.1


###Create Comment
POST http://localhost:3030/create-comment HTTP/1.1
content-type: application/json

{   
    
    "email":"jorge@noyola.com",
    "idPost":1,
    "Content":"No llores papi"
}

###Listar todos los comentarios
GET http://localhost:3030/get-comments HTTP/1.1

###Obtener publicaciones de un usuario
GET http://localhost:3030/get-posts/5 HTTP/1.1

###Obtener comentarios de una publicacion
GET http://localhost:3030/get-comments/1 HTTP/1.1